name: panopoly-1
recipe: drupal7
config:
  webroot: .
  php: 'PHP_VERSION'
  drush: '8.4.*'
services:
  appserver:
    overrides:
      environment:
        PANOPOLY_BEHAT_SCREENSHOT_PATH: '/app/sites/default/files/screenshots'
        PANOPOLY_BEHAT_WINDOW_SIZE: "1920x1080"
        PANOPOLY_BEHAT_FLAG_PHP_NOTICES: 1
    build:
      - mkdir -p /app/sites/default/files/screenshots
  selenium:
    type: compose
    moreHttpPorts:
      - '7900'
    services:
      image: selenium/standalone-chrome:100.0-20220405
      environment:
        SCREEN_WIDTH: "1920"
        SCREEN_HEIGHT: "1080"
        SCREEN_DEPTH: "24"
      shm_size: 2gb
      ports:
        - '7900'
      command: /opt/bin/entry_point.sh
tooling:
  behat:
    service: appserver
    description: Run behat tests locally.
    cmd: >-
      /app/profiles/panopoly/vendor/bin/behat
  robo:
    service: appserver
    description: Run robo.
    cmd: >-
      /app/vendor/bin/robo
